DROP TABLE scin_db.pub_cell_line;
CREATE TABLE scin_db.pub_cell_line
(
  id          int(11)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name   varchar(100)
);


use scin_db;
insert into pub_cell_line (name) values ('13C4');
insert into pub_cell_line (name) values ('143 B');
insert into pub_cell_line (name) values ('143B');
insert into pub_cell_line (name) values ('2 BD4 E4 K99');
insert into pub_cell_line (name) values ('26 CB1');
insert into pub_cell_line (name) values ('293');
insert into pub_cell_line (name) values ('2E10-H2');
insert into pub_cell_line (name) values ('2HX-2');
insert into pub_cell_line (name) values ('3 C9-D11-H11');
insert into pub_cell_line (name) values ('3 E 1');
insert into pub_cell_line (name) values ('34-5-8 S');
insert into pub_cell_line (name) values ('3A sub E');
insert into pub_cell_line (name) values ('3T3');
insert into pub_cell_line (name) values ('3T3 clone A31');
insert into pub_cell_line (name) values ('3T3 L1');
insert into pub_cell_line (name) values ('3T3 Swiss Albino');
insert into pub_cell_line (name) values ('3T3');
insert into pub_cell_line (name) values ('3T3-L1');
insert into pub_cell_line (name) values ('3T3-MSV');
insert into pub_cell_line (name) values ('3T3-Swiss albino');
insert into pub_cell_line (name) values ('3T6');
insert into pub_cell_line (name) values ('3T6-Swiss albino');
insert into pub_cell_line (name) values ('3T6-Swiss Albino');
insert into pub_cell_line (name) values ('4/4 RM-4');
insert into pub_cell_line (name) values ('45.6.TG1.7');
insert into pub_cell_line (name) values ('4H1-A7');
insert into pub_cell_line (name) values ('5 C 9');
insert into pub_cell_line (name) values ('5637');
insert into pub_cell_line (name) values ('6-23 ');
insert into pub_cell_line (name) values ('7 D4');
insert into pub_cell_line (name) values ('7-TD-1');
insert into pub_cell_line (name) values ('70Z/3');
insert into pub_cell_line (name) values ('72 A1');
insert into pub_cell_line (name) values ('72A1');
insert into pub_cell_line (name) values ('74-11-10');
insert into pub_cell_line (name) values ('74-12-4');
insert into pub_cell_line (name) values ('74-22-15');
insert into pub_cell_line (name) values ('74-9-3');
insert into pub_cell_line (name) values ('76-7-4');
insert into pub_cell_line (name) values ('7C2C5C12');
insert into pub_cell_line (name) values ('9 BG 5');
insert into pub_cell_line (name) values ('9-4-3');
insert into pub_cell_line (name) values ('A 172');
insert into pub_cell_line (name) values ('A 375');
insert into pub_cell_line (name) values ('A 72');
insert into pub_cell_line (name) values ('A-10');
insert into pub_cell_line (name) values ('A-172');
insert into pub_cell_line (name) values ('A-204');
insert into pub_cell_line (name) values ('A-427');
insert into pub_cell_line (name) values ('A-431');
insert into pub_cell_line (name) values ('A-498');
insert into pub_cell_line (name) values ('A-549');
insert into pub_cell_line (name) values ('A-704');
insert into pub_cell_line (name) values ('A-72');
insert into pub_cell_line (name) values ('A.704');
insert into pub_cell_line (name) values ('A375');
insert into pub_cell_line (name) values ('A431');
insert into pub_cell_line (name) values ('A549');
insert into pub_cell_line (name) values ('A6');
insert into pub_cell_line (name) values ('A673');
insert into pub_cell_line (name) values ('A7r5');
insert into pub_cell_line (name) values ('A9');
insert into pub_cell_line (name) values ('ACHN');
insert into pub_cell_line (name) values ('AE-1');
insert into pub_cell_line (name) values ('AE-2');
insert into pub_cell_line (name) values ('Aedes aegypti');
insert into pub_cell_line (name) values ('Aedes albopictus');
insert into pub_cell_line (name) values ('AGS');
insert into pub_cell_line (name) values ('AHL-1');
insert into pub_cell_line (name) values ('AK-D');
insert into pub_cell_line (name) values ('Amdur II');
insert into pub_cell_line (name) values ('Antheraea cells');
insert into pub_cell_line (name) values ('AR42J');
insert into pub_cell_line (name) values ('ARH 77');
insert into pub_cell_line (name) values ('AsPC-1');
insert into pub_cell_line (name) values ('AtT-20/D16v-F2');
insert into pub_cell_line (name) values ('AtT20');
insert into pub_cell_line (name) values ('AV 3');
insert into pub_cell_line (name) values ('AV3');
insert into pub_cell_line (name) values ('B 95.8');
insert into pub_cell_line (name) values ('B/C.Sk');
insert into pub_cell_line (name) values ('B14-150');
insert into pub_cell_line (name) values ('B14FAF28-G3');
insert into pub_cell_line (name) values ('B16-F0');
insert into pub_cell_line (name) values ('B16-F1');
insert into pub_cell_line (name) values ('B2-1');
insert into pub_cell_line (name) values ('B2.Sp');
insert into pub_cell_line (name) values ('B69');
insert into pub_cell_line (name) values ('B95-8');
insert into pub_cell_line (name) values ('B95.8');
insert into pub_cell_line (name) values ('BALB 3T12-3');
insert into pub_cell_line (name) values ('BALB 3T3 clone A31');
insert into pub_cell_line (name) values ('BALB/3T12-3');
insert into pub_cell_line (name) values ('BALB/3T3 clone A31');
insert into pub_cell_line (name) values ('BB');
insert into pub_cell_line (name) values ('BC3H1');
insert into pub_cell_line (name) values ('BCE C/D-1b');
insert into pub_cell_line (name) values ('BCL1 Clone CW13.20-3B3');
insert into pub_cell_line (name) values ('BeWo');
insert into pub_cell_line (name) values ('BF-2');
insert into pub_cell_line (name) values ('BHK 21 ');
insert into pub_cell_line (name) values ('BHK 21 clone 13');
insert into pub_cell_line (name) values ('BHK-21');
insert into pub_cell_line (name) values ('BHK-21 clone 13');
insert into pub_cell_line (name) values ('BHK21C13-3P');
insert into pub_cell_line (name) values ('BL-3');
insert into pub_cell_line (name) values ('BLO-11');
insert into pub_cell_line (name) values ('BNL CL.2');
insert into pub_cell_line (name) values ('BNL SV A.8');
insert into pub_cell_line (name) values ('BRL 3A');
insert into pub_cell_line (name) values ('BS-C-1');
insert into pub_cell_line (name) values ('BSC-1');
insert into pub_cell_line (name) values ('BSC1');
insert into pub_cell_line (name) values ('BT');
insert into pub_cell_line (name) values ('BT-20');
insert into pub_cell_line (name) values ('BT-474');
insert into pub_cell_line (name) values ('Bu ');
insert into pub_cell_line (name) values ('BUD-8');
insert into pub_cell_line (name) values ('BW5147.G.1.4.OUAR.1');
insert into pub_cell_line (name) values ('BXPC-3');
insert into pub_cell_line (name) values ('BxPC-3');
insert into pub_cell_line (name) values ('C 1271');
insert into pub_cell_line (name) values ('C-4 II');
insert into pub_cell_line (name) values ('C-4I');
insert into pub_cell_line (name) values ('C127I');
insert into pub_cell_line (name) values ('C211');
insert into pub_cell_line (name) values ('C2C12');
insert into pub_cell_line (name) values ('C32');
insert into pub_cell_line (name) values ('C3H/10T1/2 clone 8');
insert into pub_cell_line (name) values ('C3H/MCA clone 16');
insert into pub_cell_line (name) values ('C6');
insert into pub_cell_line (name) values ('Ca Ski');
insert into pub_cell_line (name) values ('CA-46');
insert into pub_cell_line (name) values ('CA46');
insert into pub_cell_line (name) values ('Caco-2');
insert into pub_cell_line (name) values ('CACO-2');
insert into pub_cell_line (name) values ('Caco-2');
insert into pub_cell_line (name) values ('CACO-2');
insert into pub_cell_line (name) values ('Caco-2');
insert into pub_cell_line (name) values ('CAKI 2');
insert into pub_cell_line (name) values ('CAKI-1');
insert into pub_cell_line (name) values ('Caki-1');
insert into pub_cell_line (name) values ('CAKI-2');
insert into pub_cell_line (name) values ('Caki-2');
insert into pub_cell_line (name) values ('CALU 1');
insert into pub_cell_line (name) values ('CaLu-1');
insert into pub_cell_line (name) values ('Calu-3');
insert into pub_cell_line (name) values ('Calu-6');
insert into pub_cell_line (name) values ('CAPAN 1');
insert into pub_cell_line (name) values ('CAPAN 2');
insert into pub_cell_line (name) values ('CAPAN-1');
insert into pub_cell_line (name) values ('CAPAN-2');
insert into pub_cell_line (name) values ('Capan-2');
insert into pub_cell_line (name) values ('CAR');
insert into pub_cell_line (name) values ('CCD 13Lu');
insert into pub_cell_line (name) values ('CCD 16Lu');
insert into pub_cell_line (name) values ('CCD 18Lu');
insert into pub_cell_line (name) values ('CCD 19Lu');
insert into pub_cell_line (name) values ('CCD 25Lu');
insert into pub_cell_line (name) values ('CCD 8Lu');
insert into pub_cell_line (name) values ('CCD-11Lu');
insert into pub_cell_line (name) values ('CCD-29Lu');
insert into pub_cell_line (name) values ('CCD-32Lu');
insert into pub_cell_line (name) values ('CCD-33Lu');
insert into pub_cell_line (name) values ('CCD-34Lu');
insert into pub_cell_line (name) values ('CCD-37Lu');
insert into pub_cell_line (name) values ('CCD-39Lu');
insert into pub_cell_line (name) values ('CCF-STTG1');
insert into pub_cell_line (name) values ('CCRF S 180 II');
insert into pub_cell_line (name) values ('CCRF S-180 II');
insert into pub_cell_line (name) values ('CCRF-CEM');
insert into pub_cell_line (name) values ('CCRF-HSB-2');
insert into pub_cell_line (name) values ('CCRF-SB');
insert into pub_cell_line (name) values ('CEM-CM3');
insert into pub_cell_line (name) values ('CESS');
insert into pub_cell_line (name) values ('CF2Th');
insert into pub_cell_line (name) values ('Cf2Th');
insert into pub_cell_line (name) values ('CFPAC-1');
insert into pub_cell_line (name) values ('Chang liver');
insert into pub_cell_line (name) values ('Chang Liver');
insert into pub_cell_line (name) values ('Chang liver');
insert into pub_cell_line (name) values ('CHH-1');
insert into pub_cell_line (name) values ('CHO K1');
insert into pub_cell_line (name) values ('CHO-DHFR -');
insert into pub_cell_line (name) values ('CHO-K1');
insert into pub_cell_line (name) values ('CHO/dhFr-');
insert into pub_cell_line (name) values ('CHP 3');
insert into pub_cell_line (name) values ('CHP 3 ');
insert into pub_cell_line (name) values ('CHP 4');
insert into pub_cell_line (name) values ('CHP 4 ');
insert into pub_cell_line (name) values ('CHSE 214');
insert into pub_cell_line (name) values ('CHSE-214');
insert into pub_cell_line (name) values ('Citrullinemia');
insert into pub_cell_line (name) values ('CL-S1');
insert into pub_cell_line (name) values ('Clone 1-5c-4');
insert into pub_cell_line (name) values ('Clone 1-5c-4 WKD of Chang Conjunctiva');
insert into pub_cell_line (name) values ('Clone 9');
insert into pub_cell_line (name) values ('Clone C6/36');
insert into pub_cell_line (name) values ('Clone M-3');
insert into pub_cell_line (name) values ('CMT 93');
insert into pub_cell_line (name) values ('CNC 127I');
insert into pub_cell_line (name) values ('COLO 201');
insert into pub_cell_line (name) values ('COLO 205');
insert into pub_cell_line (name) values ('COLO 320DM');
insert into pub_cell_line (name) values ('COLO 320HSR');
insert into pub_cell_line (name) values ('COLO 829');
insert into pub_cell_line (name) values ('COLO-320');
insert into pub_cell_line (name) values ('COLO-818');
insert into pub_cell_line (name) values ('Cor Per');
insert into pub_cell_line (name) values ('COS-1');
insert into pub_cell_line (name) values ('COS-7');
insert into pub_cell_line (name) values ('CP132');
insert into pub_cell_line (name) values ('CPA');
insert into pub_cell_line (name) values ('CPA 47');
insert into pub_cell_line (name) values ('CPAE');
insert into pub_cell_line (name) values ('CRE BAG2');
insert into pub_cell_line (name) values ('CRFK');
insert into pub_cell_line (name) values ('CRFK ');
insert into pub_cell_line (name) values ('Cri du Chat');
insert into pub_cell_line (name) values ('CTLL-2');
insert into pub_cell_line (name) values ('CV 1');
insert into pub_cell_line (name) values ('CV-1');
insert into pub_cell_line (name) values ('CVC 7');
insert into pub_cell_line (name) values ('D 17');
insert into pub_cell_line (name) values ('D10.G4.1');
insert into pub_cell_line (name) values ('D17');
insert into pub_cell_line (name) values ('Da Mo');
insert into pub_cell_line (name) values ('Daudi');
insert into pub_cell_line (name) values ('DAUDI');
insert into pub_cell_line (name) values ('Daudi');
insert into pub_cell_line (name) values ('DB 9 G.8');
insert into pub_cell_line (name) values ('DB1-Tes');
insert into pub_cell_line (name) values ('DBS-FCL-2');
insert into pub_cell_line (name) values ('DBS-FRhL-2');
insert into pub_cell_line (name) values ('DBTRG.05MG');
insert into pub_cell_line (name) values ('DDT1-MF2');
insert into pub_cell_line (name) values ('DeDe');
insert into pub_cell_line (name) values ('DEDE');
insert into pub_cell_line (name) values ('Detroit 510');
insert into pub_cell_line (name) values ('Detroit 525');
insert into pub_cell_line (name) values ('Detroit 529');
insert into pub_cell_line (name) values ('Detroit 532');
insert into pub_cell_line (name) values ('Detroit 539');
insert into pub_cell_line (name) values ('Detroit 548');
insert into pub_cell_line (name) values ('Detroit 551');
insert into pub_cell_line (name) values ('Detroit 562');
insert into pub_cell_line (name) values ('Detroit 573');
insert into pub_cell_line (name) values ('DH82');
insert into pub_cell_line (name) values ('DK');
insert into pub_cell_line (name) values ('DLD-1');
insert into pub_cell_line (name) values ('DMS 153');
insert into pub_cell_line (name) values ('DMS 53');
insert into pub_cell_line (name) values ('DMS 79');
insert into pub_cell_line (name) values ('DoCl1 ');
insert into pub_cell_line (name) values ('DON');
insert into pub_cell_line (name) values ('DU 145');
insert into pub_cell_line (name) values ('DU-145');
insert into pub_cell_line (name) values ('Duck embryo');
insert into pub_cell_line (name) values ('Duck Embryo');
insert into pub_cell_line (name) values ('E.Derm');
insert into pub_cell_line (name) values ('E.H.IV ');
insert into pub_cell_line (name) values ('EB-1');
insert into pub_cell_line (name) values ('EBTr');
insert into pub_cell_line (name) values ('ECV304');
insert into pub_cell_line (name) values ('Ehrlich-Lettre Ascites strain E');
insert into pub_cell_line (name) values ('EIAV 12E8.1');
insert into pub_cell_line (name) values ('EJG');
insert into pub_cell_line (name) values ('EL4');
insert into pub_cell_line (name) values ('Ep 16');
insert into pub_cell_line (name) values ('ESK-4');
insert into pub_cell_line (name) values ('F9');
insert into pub_cell_line (name) values ('FB2.Sp');
insert into pub_cell_line (name) values ('FBHE');
insert into pub_cell_line (name) values ('Fc 2 Lu');
insert into pub_cell_line (name) values ('Fc 3 Tg');
insert into pub_cell_line (name) values ('Fc2Lu');
insert into pub_cell_line (name) values ('Fc3Tg');
insert into pub_cell_line (name) values ('FeLV 3281');
insert into pub_cell_line (name) values ('Fer Ray');
insert into pub_cell_line (name) values ('FHM');
insert into pub_cell_line (name) values ('FL');
insert into pub_cell_line (name) values ('FoLu');
insert into pub_cell_line (name) values ('FR');
insert into pub_cell_line (name) values ('FRhK-4');
insert into pub_cell_line (name) values ('FRTL-5');
insert into pub_cell_line (name) values ('FT');
insert into pub_cell_line (name) values ('G-292 Clone A141B1');
insert into pub_cell_line (name) values ('G-361');
insert into pub_cell_line (name) values ('G-401');
insert into pub_cell_line (name) values ('G-402');
insert into pub_cell_line (name) values ('G-7');
insert into pub_cell_line (name) values ('G-8');
insert into pub_cell_line (name) values ('G.8');
insert into pub_cell_line (name) values ('GCT');
insert into pub_cell_line (name) values ('GeLu');
insert into pub_cell_line (name) values ('GH 1');
insert into pub_cell_line (name) values ('GH 3');
insert into pub_cell_line (name) values ('GH1');
insert into pub_cell_line (name) values ('GH3');
insert into pub_cell_line (name) values ('GIRARDI HEART');
insert into pub_cell_line (name) values ('GK 1.5');
insert into pub_cell_line (name) values ('GL-1');
insert into pub_cell_line (name) values ('Grunt Fin ');
insert into pub_cell_line (name) values ('GS-109-V-20');
insert into pub_cell_line (name) values ('GS-109-V-34');
insert into pub_cell_line (name) values ('GS-109-V-63');
insert into pub_cell_line (name) values ('H 16-L10-4R 5');
insert into pub_cell_line (name) values ('H 9');
insert into pub_cell_line (name) values ('H-4-II-E');
insert into pub_cell_line (name) values ('H2.35');
insert into pub_cell_line (name) values ('H33HJ-JA1');
insert into pub_cell_line (name) values ('H4');
insert into pub_cell_line (name) values ('H4-II-E-C3');
insert into pub_cell_line (name) values ('H460');
insert into pub_cell_line (name) values ('H4S');
insert into pub_cell_line (name) values ('H4TG');
insert into pub_cell_line (name) values ('H69');
insert into pub_cell_line (name) values ('H9');
insert into pub_cell_line (name) values ('H9c2 ');
insert into pub_cell_line (name) values ('H9c2');
insert into pub_cell_line (name) values ('Hak');
insert into pub_cell_line (name) values ('HBL-100');
insert into pub_cell_line (name) values ('HCT 116');
insert into pub_cell_line (name) values ('HCT-15');
insert into pub_cell_line (name) values ('HCT-8');
insert into pub_cell_line (name) values ('HEC-1-B');
insert into pub_cell_line (name) values ('HEL 299');
insert into pub_cell_line (name) values ('HeLa');
insert into pub_cell_line (name) values ('HeLA');
insert into pub_cell_line (name) values ('HeLa');
insert into pub_cell_line (name) values ('HeLa 229');
insert into pub_cell_line (name) values ('HeLa B');
insert into pub_cell_line (name) values ('HeLa S 3');
insert into pub_cell_line (name) values ('HeLa S3');
insert into pub_cell_line (name) values ('HELA-S3');
insert into pub_cell_line (name) values ('HeLa229');
insert into pub_cell_line (name) values ('Hep 2');
insert into pub_cell_line (name) values ('Hep 3B');
insert into pub_cell_line (name) values ('Hep G2');
insert into pub_cell_line (name) values ('HEp-2');
insert into pub_cell_line (name) values ('Hep-2');
insert into pub_cell_line (name) values ('HEP-3B');
insert into pub_cell_line (name) values ('HEP-G2');
insert into pub_cell_line (name) values ('Hep2');
insert into pub_cell_line (name) values ('Hep2 ');
insert into pub_cell_line (name) values ('HEPA 1-6');
insert into pub_cell_line (name) values ('Hepa 1-6');
insert into pub_cell_line (name) values ('Hepa-1c1c7');
insert into pub_cell_line (name) values ('Hepa-1clc7');
insert into pub_cell_line (name) values ('HEPM');
insert into pub_cell_line (name) values ('HFL1');
insert into pub_cell_line (name) values ('HG 261');
insert into pub_cell_line (name) values ('HG261');
insert into pub_cell_line (name) values ('HL 60');
insert into pub_cell_line (name) values ('HL-60');
insert into pub_cell_line (name) values ('HL60');
insert into pub_cell_line (name) values ('HLF-a');
insert into pub_cell_line (name) values ('HOS');
insert into pub_cell_line (name) values ('HOS ');
insert into pub_cell_line (name) values ('Hs 27');
insert into pub_cell_line (name) values ('Hs 431');
insert into pub_cell_line (name) values ('Hs 578Bst');
insert into pub_cell_line (name) values ('Hs 578T');
insert into pub_cell_line (name) values ('Hs 633T');
insert into pub_cell_line (name) values ('Hs 68');
insert into pub_cell_line (name) values ('Hs 683');
insert into pub_cell_line (name) values ('Hs 863.T');
insert into pub_cell_line (name) values ('HS 883.T');
insert into pub_cell_line (name) values ('HS 888 Lu');
insert into pub_cell_line (name) values ('Hs 888Lu');
insert into pub_cell_line (name) values ('Hs-27');
insert into pub_cell_line (name) values ('HS-Sultan');
insert into pub_cell_line (name) values ('HSDM1C1');
insert into pub_cell_line (name) values ('HT 1080');
insert into pub_cell_line (name) values ('HT 1197');
insert into pub_cell_line (name) values ('HT 1376');
insert into pub_cell_line (name) values ('HT-1080');
insert into pub_cell_line (name) values ('HT-29');
insert into pub_cell_line (name) values ('HT2 Clone A5E');
insert into pub_cell_line (name) values ('HT29');
insert into pub_cell_line (name) values ('HuT 102');
insert into pub_cell_line (name) values ('HuT 78');
insert into pub_cell_line (name) values ('HUT-78');
insert into pub_cell_line (name) values ('HuTu 80');
insert into pub_cell_line (name) values ('HVS-SILVA 40');
insert into pub_cell_line (name) values ('I 10');
insert into pub_cell_line (name) values ('I-10');
insert into pub_cell_line (name) values ('IA-Xs SBR');
insert into pub_cell_line (name) values ('IBRS-2 D10');
insert into pub_cell_line (name) values ('IC-21');
insert into pub_cell_line (name) values ('ICR-2A');
insert into pub_cell_line (name) values ('IEC 18');
insert into pub_cell_line (name) values ('IEC 6');
insert into pub_cell_line (name) values ('IEC-6');
insert into pub_cell_line (name) values ('IgH-2');
insert into pub_cell_line (name) values ('IM 9');
insert into pub_cell_line (name) values ('IM-9');
insert into pub_cell_line (name) values ('IMR 31 Bu');
insert into pub_cell_line (name) values ('IMR 32');
insert into pub_cell_line (name) values ('IMR-32');
insert into pub_cell_line (name) values ('IMR-90');
insert into pub_cell_line (name) values ('Indian Muntjac');
insert into pub_cell_line (name) values ('INT 407');
insert into pub_cell_line (name) values ('Intestine 407');
insert into pub_cell_line (name) values ('J 774A.1');
insert into pub_cell_line (name) values ('J-774A.1');
insert into pub_cell_line (name) values ('J.CaM1.6');
insert into pub_cell_line (name) values ('J45.01');
insert into pub_cell_line (name) values ('J774A.1');
insert into pub_cell_line (name) values ('Ja Bos');
insert into pub_cell_line (name) values ('Jay Sen');
insert into pub_cell_line (name) values ('JEG-3');
insert into pub_cell_line (name) values ('JEG3');
insert into pub_cell_line (name) values ('Jensen sarcoma');
insert into pub_cell_line (name) values ('JH 4 clone 1');
insert into pub_cell_line (name) values ('JH4 clone 1');
insert into pub_cell_line (name) values ('JIYOYE');
insert into pub_cell_line (name) values ('Jiyoye');
insert into pub_cell_line (name) values ('JLS-V9');
insert into pub_cell_line (name) values ('K 562');
insert into pub_cell_line (name) values ('K-562');
insert into pub_cell_line (name) values ('K-BALB ');
insert into pub_cell_line (name) values ('K562');
insert into pub_cell_line (name) values ('K6H6/B5');
insert into pub_cell_line (name) values ('KATO III°');
insert into pub_cell_line (name) values ('KATO-III');
insert into pub_cell_line (name) values ('KB');
insert into pub_cell_line (name) values ('KG-1');
insert into pub_cell_line (name) values ('KG-1a');
insert into pub_cell_line (name) values ('KG1a');
insert into pub_cell_line (name) values ('KHOS-240S');
insert into pub_cell_line (name) values ('KHOS-312H');
insert into pub_cell_line (name) values ('KHOS/NP');
insert into pub_cell_line (name) values ('KLN 205');
insert into pub_cell_line (name) values ('KNRK');
insert into pub_cell_line (name) values ('L 1210');
insert into pub_cell_line (name) values ('L 132');
insert into pub_cell_line (name) values ('L 21.6');
insert into pub_cell_line (name) values ('L 243');
insert into pub_cell_line (name) values ('L 5.1');
insert into pub_cell_line (name) values ('L-1210');
insert into pub_cell_line (name) values ('L-132');
insert into pub_cell_line (name) values ('L-2');
insert into pub_cell_line (name) values ('L-M');
insert into pub_cell_line (name) values ('L-M ');
insert into pub_cell_line (name) values ('L-M');
insert into pub_cell_line (name) values ('L1210');
insert into pub_cell_line (name) values ('L132');
insert into pub_cell_line (name) values ('L5178Y-R ');
insert into pub_cell_line (name) values ('L5178Y-S ');
insert into pub_cell_line (name) values ('L6');
insert into pub_cell_line (name) values ('L8');
insert into pub_cell_line (name) values ('LA-4');
insert into pub_cell_line (name) values ('LBRM-33-1A5');
insert into pub_cell_line (name) values ('LC 540');
insert into pub_cell_line (name) values ('LC540');
insert into pub_cell_line (name) values ('LL/2');
insert into pub_cell_line (name) values ('LL24');
insert into pub_cell_line (name) values ('LL29 ');
insert into pub_cell_line (name) values ('LL47 ');
insert into pub_cell_line (name) values ('LL86 ');
insert into pub_cell_line (name) values ('LLC-MK2');
insert into pub_cell_line (name) values ('LLC-PK1');
insert into pub_cell_line (name) values ('LLC-RK1');
insert into pub_cell_line (name) values ('LLC-WRC 256');
insert into pub_cell_line (name) values ('LLCMK2 ');
insert into pub_cell_line (name) values ('LM from NCTC clone 929');
insert into pub_cell_line (name) values ('LM TK negative');
insert into pub_cell_line (name) values ('LNCaP.FGC');
insert into pub_cell_line (name) values ('LoVo');
insert into pub_cell_line (name) values ('LS 123');
insert into pub_cell_line (name) values ('LS 180');
insert into pub_cell_line (name) values ('LS174T');
insert into pub_cell_line (name) values ('LS180');
insert into pub_cell_line (name) values ('M 1');
insert into pub_cell_line (name) values ('M-2E6');
insert into pub_cell_line (name) values ('M-MSV-BALB/3T3');
insert into pub_cell_line (name) values ('M. dunni ');
insert into pub_cell_line (name) values ('M1');
insert into pub_cell_line (name) values ('M1WT3');
insert into pub_cell_line (name) values ('M2-1C6-4R3');
insert into pub_cell_line (name) values ('M3 Clone M-3');
insert into pub_cell_line (name) values ('mAB 35');
insert into pub_cell_line (name) values ('MALME-3M');
insert into pub_cell_line (name) values ('MB-III ');
insert into pub_cell_line (name) values ('Mc Coy');
insert into pub_cell_line (name) values ('MC-116');
insert into pub_cell_line (name) values ('MC/CAR');
insert into pub_cell_line (name) values ('MC116');
insert into pub_cell_line (name) values ('MCA-RH 7777');
insert into pub_cell_line (name) values ('McA-RH7777');
insert into pub_cell_line (name) values ('McCoy');
insert into pub_cell_line (name) values ('MCF 7');
insert into pub_cell_line (name) values ('MCF-7');
insert into pub_cell_line (name) values ('MCF7');
insert into pub_cell_line (name) values ('MDA-MB-134-VI');
insert into pub_cell_line (name) values ('MDA-MB-157');
insert into pub_cell_line (name) values ('MDA-MB-231');
insert into pub_cell_line (name) values ('MDA-MB-361');
insert into pub_cell_line (name) values ('MDA-MB-415');
insert into pub_cell_line (name) values ('MDA-MB-453');
insert into pub_cell_line (name) values ('MDBK');
insert into pub_cell_line (name) values ('MDBK ');
insert into pub_cell_line (name) values ('MDCK');
insert into pub_cell_line (name) values ('MDCK ');
insert into pub_cell_line (name) values ('MDOK');
insert into pub_cell_line (name) values ('MDTC RP 19');
insert into pub_cell_line (name) values ('MEG-01');
insert into pub_cell_line (name) values ('MEL III');
insert into pub_cell_line (name) values ('MES-SA');
insert into pub_cell_line (name) values ('MES-SA/Dx-5');
insert into pub_cell_line (name) values ('MG-63');
insert into pub_cell_line (name) values ('MH 1 C 1');
insert into pub_cell_line (name) values ('MH-S');
insert into pub_cell_line (name) values ('MH1C1');
insert into pub_cell_line (name) values ('MIA PaCa-2');
insert into pub_cell_line (name) values ('MIA-Pa-Ca-2');
insert into pub_cell_line (name) values ('MiCl1');
insert into pub_cell_line (name) values ('MiCL1 ');
insert into pub_cell_line (name) values ('MK-D6');
insert into pub_cell_line (name) values ('MLA 144');
insert into pub_cell_line (name) values ('MLA144');
insert into pub_cell_line (name) values ('MLg');
insert into pub_cell_line (name) values ('MMT-060562');
insert into pub_cell_line (name) values ('MNNG/HOS ');
insert into pub_cell_line (name) values ('Mo-B');
insert into pub_cell_line (name) values ('MOLT-3');
insert into pub_cell_line (name) values ('MOLT-4');
insert into pub_cell_line (name) values ('MOP-8');
insert into pub_cell_line (name) values ('MOPC 315');
insert into pub_cell_line (name) values ('MOPC 31C');
insert into pub_cell_line (name) values ('MPC-11');
insert into pub_cell_line (name) values ('Mpf');
insert into pub_cell_line (name) values ('MPK');
insert into pub_cell_line (name) values ('MRC 5');
insert into pub_cell_line (name) values ('MRC-5');
insert into pub_cell_line (name) values ('MRC-9');
insert into pub_cell_line (name) values ('MRSS-1');
insert into pub_cell_line (name) values ('Mv 1 Lu');
insert into pub_cell_line (name) values ('Mv 1 Lu ');
insert into pub_cell_line (name) values ('MV 4-11');
insert into pub_cell_line (name) values ('Mv.1.Lu');
insert into pub_cell_line (name) values ('MV4-11');
insert into pub_cell_line (name) values ('N1-S1');
insert into pub_cell_line (name) values ('N1E-115');
insert into pub_cell_line (name) values ('Namalwa');
insert into pub_cell_line (name) values ('NAMALWA');
insert into pub_cell_line (name) values ('NB4 1A3');
insert into pub_cell_line (name) values ('NB41A3');
insert into pub_cell_line (name) values ('NBT-II');
insert into pub_cell_line (name) values ('NC-37');
insert into pub_cell_line (name) values ('NCI-H292');
insert into pub_cell_line (name) values ('NCI-H322');
insert into pub_cell_line (name) values ('NCI-H358');
insert into pub_cell_line (name) values ('NCI-H716');
insert into pub_cell_line (name) values ('NCI-H727');
insert into pub_cell_line (name) values ('NCI-H929');
insert into pub_cell_line (name) values ('NCTC 2071');
insert into pub_cell_line (name) values ('NCTC 3749');
insert into pub_cell_line (name) values ('NCTC 4093');
insert into pub_cell_line (name) values ('NCTC 4206');
insert into pub_cell_line (name) values ('NCTC clone 1469');
insert into pub_cell_line (name) values ('NCTC clone 2472');
insert into pub_cell_line (name) values ('NCTC clone 2555');
insert into pub_cell_line (name) values ('NCTC clone 3526');
insert into pub_cell_line (name) values ('NCTC clone 929');
insert into pub_cell_line (name) values ('Neuro 2a');
insert into pub_cell_line (name) values ('NEURO-2A');
insert into pub_cell_line (name) values ('Neuro-2a');
insert into pub_cell_line (name) values ('NFS-25 C-3');
insert into pub_cell_line (name) values ('NFS-5 C1');
insert into pub_cell_line (name) values ('NFS-70 C10');
insert into pub_cell_line (name) values ('NIH 3T3');
insert into pub_cell_line (name) values ('NIH-3T3');
insert into pub_cell_line (name) values ('NIH-3T3D4');
insert into pub_cell_line (name) values ('NIH/3T3');
insert into pub_cell_line (name) values ('NIH:OVCAR-3');
insert into pub_cell_line (name) values ('NMuMG');
insert into pub_cell_line (name) values ('NOR 10');
insert into pub_cell_line (name) values ('NRK 49F');
insert into pub_cell_line (name) values ('NRK-49F');
insert into pub_cell_line (name) values ('NRK-52E');
insert into pub_cell_line (name) values ('NULLI-SCC1');
insert into pub_cell_line (name) values ('OA1');
insert into pub_cell_line (name) values ('OHH1.K');
insert into pub_cell_line (name) values ('OK');
insert into pub_cell_line (name) values ('OKT 3');
insert into pub_cell_line (name) values ('OKT 4');
insert into pub_cell_line (name) values ('OKT 8');
insert into pub_cell_line (name) values ('OMK ');
insert into pub_cell_line (name) values ('Or De');
insert into pub_cell_line (name) values ('OVCAR-3');
insert into pub_cell_line (name) values ('P 3 HR 1');
insert into pub_cell_line (name) values ('P-815');
insert into pub_cell_line (name) values ('P19');
insert into pub_cell_line (name) values ('P3 88 D1');
insert into pub_cell_line (name) values ('P3 NS1 Ag4');
insert into pub_cell_line (name) values ('P3/NS1/1-Ag4-1');
insert into pub_cell_line (name) values ('P3/NS1/1-Ag4.1');
insert into pub_cell_line (name) values ('P3/NSI/1-AG4-1');
insert into pub_cell_line (name) values ('P388.D1 ');
insert into pub_cell_line (name) values ('P388D1');
insert into pub_cell_line (name) values ('P388D1 ');
insert into pub_cell_line (name) values ('P3HR-1');
insert into pub_cell_line (name) values ('P3NP/PFN');
insert into pub_cell_line (name) values ('P3U1');
insert into pub_cell_line (name) values ('P3X63Ag8');
insert into pub_cell_line (name) values ('P3X63Ag8.653');
insert into pub_cell_line (name) values ('P3X63Ag8U.1');
insert into pub_cell_line (name) values ('P815');
insert into pub_cell_line (name) values ('PA-1');
insert into pub_cell_line (name) values ('PA317');
insert into pub_cell_line (name) values ('PAB-100');
insert into pub_cell_line (name) values ('PAB-122');
insert into pub_cell_line (name) values ('PANC-1');
insert into pub_cell_line (name) values ('PC 61-5-3');
insert into pub_cell_line (name) values ('PC-12');
insert into pub_cell_line (name) values ('PC-3');
insert into pub_cell_line (name) values ('PEG 1-6');
insert into pub_cell_line (name) values ('PG-4');
insert into pub_cell_line (name) values ('PG13');
insert into pub_cell_line (name) values ('PI.1 Ut');
insert into pub_cell_line (name) values ('PK 15');
insert into pub_cell_line (name) values ('PK');
insert into pub_cell_line (name) values ('PLC/PRF/5');
insert into pub_cell_line (name) values ('PLC/PRF/5 ');
insert into pub_cell_line (name) values ('PSI 2 BAG alpha');
insert into pub_cell_line (name) values ('Pt K1');
insert into pub_cell_line (name) values ('Pt K1 ');
insert into pub_cell_line (name) values ('Ptk1');
insert into pub_cell_line (name) values ('Ptk2');
insert into pub_cell_line (name) values ('Pu-518');
insert into pub_cell_line (name) values ('QT 6');
insert into pub_cell_line (name) values ('R 2 C');
insert into pub_cell_line (name) values ('R 9 ab');
insert into pub_cell_line (name) values ('R D');
insert into pub_cell_line (name) values ('R2C');
insert into pub_cell_line (name) values ('R63');
insert into pub_cell_line (name) values ('R9ab');
insert into pub_cell_line (name) values ('RAB-9');
insert into pub_cell_line (name) values ('RAG');
insert into pub_cell_line (name) values ('Raji');
insert into pub_cell_line (name) values ('RaJi');
insert into pub_cell_line (name) values ('Raji');
insert into pub_cell_line (name) values ('RAJI');
insert into pub_cell_line (name) values ('RAMOS ');
insert into pub_cell_line (name) values ('RAT-2');
insert into pub_cell_line (name) values ('Rat2');
insert into pub_cell_line (name) values ('RAW 264');
insert into pub_cell_line (name) values ('RBL 1');
insert into pub_cell_line (name) values ('RBL-1');
insert into pub_cell_line (name) values ('RD');
insert into pub_cell_line (name) values ('RD-ES');
insert into pub_cell_line (name) values ('RFL 6');
insert into pub_cell_line (name) values ('RFL-6');
insert into pub_cell_line (name) values ('RIN-5F');
insert into pub_cell_line (name) values ('RIN-m');
insert into pub_cell_line (name) values ('RK 13');
insert into pub_cell_line (name) values ('RK13');
insert into pub_cell_line (name) values ('RPMI 1788');
insert into pub_cell_line (name) values ('RPMI 1846');
insert into pub_cell_line (name) values ('RPMI 2650');
insert into pub_cell_line (name) values ('RPMI 6666');
insert into pub_cell_line (name) values ('RPMI 7666');
insert into pub_cell_line (name) values ('RPMI 8226');
insert into pub_cell_line (name) values ('RPMI-7951');
insert into pub_cell_line (name) values ('RR 1022');
insert into pub_cell_line (name) values ('RR1022');
insert into pub_cell_line (name) values ('RT4');
insert into pub_cell_line (name) values ('RTG 2');
insert into pub_cell_line (name) values ('RTG-2');
insert into pub_cell_line (name) values ('SaOS-2');
insert into pub_cell_line (name) values ('SAOS-2');
insert into pub_cell_line (name) values ('Saos-2');
insert into pub_cell_line (name) values ('SBAC');
insert into pub_cell_line (name) values ('SC-1');
insert into pub_cell_line (name) values ('SCP');
insert into pub_cell_line (name) values ('Sf 1 Ep');
insert into pub_cell_line (name) values ('Sf 1Ep');
insert into pub_cell_line (name) values ('SF-9');
insert into pub_cell_line (name) values ('Sf9');
insert into pub_cell_line (name) values ('SHM-D33');
insert into pub_cell_line (name) values ('SiHa');
insert into pub_cell_line (name) values ('SIRC');
insert into pub_cell_line (name) values ('SJMRF');
insert into pub_cell_line (name) values ('SK LU 1');
insert into pub_cell_line (name) values ('SK-BR-3');
insert into pub_cell_line (name) values ('SK-HEP-1');
insert into pub_cell_line (name) values ('SK-LU-1');
insert into pub_cell_line (name) values ('SK-MEL-28');
insert into pub_cell_line (name) values ('SK-MES-1');
insert into pub_cell_line (name) values ('SK-N-AS');
insert into pub_cell_line (name) values ('SK-N-DZ');
insert into pub_cell_line (name) values ('SK-N-MC');
insert into pub_cell_line (name) values ('SK-N-SH');
insert into pub_cell_line (name) values ('SK-NEP-1');
insert into pub_cell_line (name) values ('SK-OV-3');
insert into pub_cell_line (name) values ('SK-PN-DW');
insert into pub_cell_line (name) values ('SK-UT-1B');
insert into pub_cell_line (name) values ('Sp1K');
insert into pub_cell_line (name) values ('Sp2/0-Ag14');
insert into pub_cell_line (name) values ('SP2/0-AG14');
insert into pub_cell_line (name) values ('SP2/0-Ag14');
insert into pub_cell_line (name) values ('Sp2/0-Ag14');
insert into pub_cell_line (name) values ('SP2/0-Ag14');
insert into pub_cell_line (name) values ('Sp2/0-Ag14');
insert into pub_cell_line (name) values ('SP2/0-AG14');
insert into pub_cell_line (name) values ('Sp2/0-Ag14');
insert into pub_cell_line (name) values ('SR-4987');
insert into pub_cell_line (name) values ('ST');
insert into pub_cell_line (name) values ('STO');
insert into pub_cell_line (name) values ('SUP-T1');
insert into pub_cell_line (name) values ('SV-T2');
insert into pub_cell_line (name) values ('SW 1116');
insert into pub_cell_line (name) values ('SW 13');
insert into pub_cell_line (name) values ('SW 1417');
insert into pub_cell_line (name) values ('SW 1463');
insert into pub_cell_line (name) values ('SW 403');
insert into pub_cell_line (name) values ('SW 48');
insert into pub_cell_line (name) values ('SW 480');
insert into pub_cell_line (name) values ('SW 620');
insert into pub_cell_line (name) values ('SW 837');
insert into pub_cell_line (name) values ('SW 948');
insert into pub_cell_line (name) values ('SW480');
insert into pub_cell_line (name) values ('SW620');
insert into pub_cell_line (name) values ('SW837');
insert into pub_cell_line (name) values ('T 24');
insert into pub_cell_line (name) values ('T 98 G');
insert into pub_cell_line (name) values ('T-47D');
insert into pub_cell_line (name) values ('T/G HA-VSMC');
insert into pub_cell_line (name) values ('T24/83');
insert into pub_cell_line (name) values ('T47D');
insert into pub_cell_line (name) values ('T84');
insert into pub_cell_line (name) values ('T98 G');
insert into pub_cell_line (name) values ('T98G');
insert into pub_cell_line (name) values ('Tb 1 Lu');
insert into pub_cell_line (name) values ('Tb 1 Lu ');
insert into pub_cell_line (name) values ('TB1 Lu ');
insert into pub_cell_line (name) values ('TCMK-1');
insert into pub_cell_line (name) values ('TE671 Subline No.2');
insert into pub_cell_line (name) values ('TGP 49');
insert into pub_cell_line (name) values ('TGP 52');
insert into pub_cell_line (name) values ('TGP 55');
insert into pub_cell_line (name) values ('TH-1 subline B1');
insert into pub_cell_line (name) values ('TH-1,Subline B1');
insert into pub_cell_line (name) values ('THP 1');
insert into pub_cell_line (name) values ('THP-1');
insert into pub_cell_line (name) values ('TK TS 13');
insert into pub_cell_line (name) values ('TK-TS 13');
insert into pub_cell_line (name) values ('TK6');
insert into pub_cell_line (name) values ('TM3');
insert into pub_cell_line (name) values ('TM4');
insert into pub_cell_line (name) values ('TRA-171');
insert into pub_cell_line (name) values ('TT');
insert into pub_cell_line (name) values ('U 937');
insert into pub_cell_line (name) values ('U-138 MG');
insert into pub_cell_line (name) values ('U-2 OS');
insert into pub_cell_line (name) values ('U-266');
insert into pub_cell_line (name) values ('U-373 MG');
insert into pub_cell_line (name) values ('U-87 MG');
insert into pub_cell_line (name) values ('U-937');
insert into pub_cell_line (name) values ('U266B1');
insert into pub_cell_line (name) values ('U373 MG');
insert into pub_cell_line (name) values ('U937');
insert into pub_cell_line (name) values ('UMR-106');
insert into pub_cell_line (name) values ('UMR-108');
insert into pub_cell_line (name) values ('UT-1');
insert into pub_cell_line (name) values ('V79-4');
insert into pub_cell_line (name) values ('VA-ES-BJ');
insert into pub_cell_line (name) values ('Vero');
insert into pub_cell_line (name) values ('VERO');
insert into pub_cell_line (name) values ('Vero');
insert into pub_cell_line (name) values ('VERO 76');
insert into pub_cell_line (name) values ('VERO C 1008');
insert into pub_cell_line (name) values ('Vero C1008');
insert into pub_cell_line (name) values ('Vero76');
insert into pub_cell_line (name) values ('VH2');
insert into pub_cell_line (name) values ('Vx2');
insert into pub_cell_line (name) values ('WEHI 164');
insert into pub_cell_line (name) values ('WEHI-164S');
insert into pub_cell_line (name) values ('WEHI-274.1');
insert into pub_cell_line (name) values ('WEHI-279');
insert into pub_cell_line (name) values ('WEHI-3');
insert into pub_cell_line (name) values ('WERI-RB-1');
insert into pub_cell_line (name) values ('WES');
insert into pub_cell_line (name) values ('Wgd5');
insert into pub_cell_line (name) values ('WI 1003');
insert into pub_cell_line (name) values ('WI 26 VA 4');
insert into pub_cell_line (name) values ('WI 26 VA4');
insert into pub_cell_line (name) values ('WI 38');
insert into pub_cell_line (name) values ('WI 38 VA 13');
insert into pub_cell_line (name) values ('WI 38VA13 Subline 2RA');
insert into pub_cell_line (name) values ('WI-1003');
insert into pub_cell_line (name) values ('WI-38');
insert into pub_cell_line (name) values ('WI-38 VA13 subline 2RA');
insert into pub_cell_line (name) values ('WiDr');
insert into pub_cell_line (name) values ('WIL2 NS');
insert into pub_cell_line (name) values ('WISH');
insert into pub_cell_line (name) values ('WM 115');
insert into pub_cell_line (name) values ('WM 266-4');
insert into pub_cell_line (name) values ('WM-115');
insert into pub_cell_line (name) values ('WRL 68');
insert into pub_cell_line (name) values ('WS1');
insert into pub_cell_line (name) values ('X63AG8.653');
insert into pub_cell_line (name) values ('XC');
insert into pub_cell_line (name) values ('Y 1');
insert into pub_cell_line (name) values ('Y-1');
insert into pub_cell_line (name) values ('Y-79');
insert into pub_cell_line (name) values ('Y1');
insert into pub_cell_line (name) values ('Y3.Ag.1.2.3');
insert into pub_cell_line (name) values ('Y3.AG.1.2.3');
insert into pub_cell_line (name) values ('Y79');
insert into pub_cell_line (name) values ('YAC-1');
insert into pub_cell_line (name) values ('YO');
insert into pub_cell_line (name) values ('ZR-75-1');
insert into pub_cell_line (name) values ('ZR-75-30');